### ISSUE TITLE
CoreML/Cuda support

### ISSUE THREAD

**Issue by chiefMarlin** [yalue/onnxruntime_go#11]
Hi,
Is there any way to utilize CoreML/Cuda hardware ?

Thanks

**Comment by yalue** [comment]
Hi,

I am actually actively working on this, and expect to be done in a maybe a week.  This is just a non-professional side project for me, so I am unable to move very quickly on big changes, but I have been planning to add support for CUDA for a while now.  Anyway, if you check back in a week or two, I hope to have a big change by then that will add support for CUDA, other session options, and more flexibility with respect to input and output tensor types.

Thanks!

**Comment by chiefMarlin** [comment]
Thanks, would you be interested in a pull request for CoreML functionality ?

**Comment by yalue** [comment]
Sure, I'd be happy to have it!  However, you'll probably want to wait until after I've my changes that will refactor a lot of the current `Session` implementation.  I also don't have the apple hardware to test CoreML, so I'd be relying on others for ensuring that it works.

**Comment by chiefMarlin** [comment]
Sounds good, let me know when you want me to submit it, i've tested it on existing code and it works pretty well

**Comment by chiefMarlin** [comment]
So the initial pr worked with coreml on osx arm64 but Im having some issues adapting the code to the new release. Would you be willing to implement coreml setOptions the same way as you did for cuda ?

**Comment by yalue** [comment]
Turns out it may have been easier than I thought... I hope.  Still haven't tested the code yet, but if you wanted to test it, the following should work now, hopefully:
```bash
git pull origin add_coreml_support
go test -v -bench=.
```
You should see the CoreML-related test and benchmark run and pass rather than get skipped.  If you get a chance, let me know if it works!

**Comment by chiefMarlin** [comment]
Impressive!
Tests work, additionally i just tested with an image recognition example and it works perfectly!
Would you like me to submit a pr with the example ?

**Comment by yalue** [comment]
That's great to hear, and thank you for checking!  Feel free to reopen this issue if you notice a memory leak in this version; it's possible that whatever is causing the leak in the fork you were using actually originated here.
