### ISSUE TITLE
Session options?

### ISSUE THREAD

**Issue by JohnGebbie** [yalue/onnxruntime_go#2]
Hello and thank you for making this.
I was wondering if there is or will be a way to set the number of threads for a session?

This is what I'm porting from python:

```
opts = onnxruntime.SessionOptions()
opts.inter_op_num_threads = 1
opts.intra_op_num_threads = 1
landmarking = onnxruntime.InferenceSession("model.onnx", opts, providers)
```

Without the thread options, like currently in my Go version, my CPU goes all the way up to 389% with seemingly no benefit in my case.

Thanks again.

**Comment by JohnGebbie** [comment]
Thank you so much! Your lines worked and then I realized gocv was using multiple threads too. I might try to make a PR if all goes to plan. I'm cheese'n!

**Comment by johngebbie** [comment]
Fab and thanks for letting me know!

I made a little [head tracking util](https://git.sr.ht/~geb/noggin) with onnxruntime_go and now I shouldn't need to patch it :)
