### ISSUE TITLE
Loading input/output names and shapes from the session

### ISSUE THREAD

**Issue by Andrewsville** [yalue/onnxruntime_go#22]
I came across this library and it's pretty damn cool :) 

Considering that names and shapes are stored insite the onnx file, I was wondering if you would be interested in having a functionality that loads them and provides them to the user.

I can imagine the Session loading this info during creation and having it stored in public properties or having getters. The only thing to keep in mind is that shapes can have dynamic dimensions (typically batch size) so it would need to be able to signalize that some dimension is dynamic (-1 or some other value).

It could even pre-create input and output tensors based on these shapes. Unfortunately, this has limitations - if you have dynamic dimensions, you cannot really tell how large tensors will the user use. But you could at least validate tensor sizes. If you have an input shape [1, 2, 3], you know that the user provided tensor has to have a size of 1*2*3. If the shape is [???, 3, 224, 224], you know that the provided tensor has to have a size divisible by 3*224*224. The only exception would be the newly added CustomDataTensor where IMO you don't know anything. But I see the CustomDataTensor as a sort of last resort solution when the go type system isn't enough.

Anyway, if this sounds like something you want in the library, I can try to provide a MR :)

**Comment by Andrewsville** [comment]
Eh, reading other issues I have found the fork https://github.com/peer-ai-org/onnxruntime_go that seems to do it. I suppose there is no need to reinvent the wheel.

**Comment by kampaidev** [comment]
Why not just use https://netron.app? Gives you more control anyways

**Comment by yalue** [comment]
As of commit d7e65a16dc633f9416 (v1.7.0), it is now possible to read input names, shapes, and types from .onnx files using the `GetInputOutputInfo` or `GetInputOutputInfoWithONNXData` functions:

https://pkg.go.dev/github.com/yalue/onnxruntime_go#GetInputOutputInfo
https://pkg.go.dev/github.com/yalue/onnxruntime_go#GetInputOutputInfoWithONNXData
