### ISSUE TITLE
Can you write a working example for float 16 on detection?

### ISSUE THREAD

**Issue by Osbornnnnn** [yalue/onnxruntime_go#28]
It is not clear how to run, your example inissue are not working((

**Comment by yalue** [comment]
The code snippet I posted along with the issues a few months ago should work, but I added a float16 MNIST example example to the `onnxruntime_go_examples` repository.  See https://github.com/yalue/onnxruntime_go_examples/tree/master/mnist_float16.  I have verified that it works, and it uses 16-bit floats.
