### ISSUE TITLE
model metadata

### ISSUE THREAD

**Issue by oldma3095** [yalue/onnxruntime_go#35]
Hi.
I noticed that the [API](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_model_metadata.html) has methods for Ort::ModelMetadata. 
Includes: input.name, input.tensor, output.name, output.tensor, format, imgsz, names ... 
![image](https://github.com/yalue/onnxruntime_go/assets/43288861/9d2f6987-f628-4e6d-a84f-44450bfc59d7)

This is very useful. 
Hope to add a function to get this information.
Thanks!

**Comment by yalue** [comment]
I just added support for `GetModelMetadata` as of commit d8bb20d9a9ee4cecc5d5f (tagged version `v1.8.0`).  You can get the metadata using [`AdvancedSession.GetModelMetadata()`](https://pkg.go.dev/github.com/yalue/onnxruntime_go@v1.8.0#GetModelMetadata):
```go
metadata, err := mySession.GetModelMetadata()
// Alternatively:
// metadata, err := onnxruntime_go.GetModelMetadata("path/to/file.onnx")
if err != nil {
    panic("Error getting metadata")
}
// ModelMetadata instances must always be cleaned up when no longer needed.
defer metadata.Destroy()

modelProducerName, err := metadata.GetProducerName()
if err != nil {
    panic("Error getting model producer name from metadata")
}
fmt.Printf("Model producer name: %s\n", modelProducerName)

// etc.
```

You mentioned input and output names and sizes in your comment, but those aren't actually provided by the `OrtModelMetadata` API.  They're actually part of a completely different set of APIs, that this library already supports.  See [this comment in the relevant issue](https://github.com/yalue/onnxruntime_go/issues/31#issuecomment-1879723583) for how to get input and output names.
