### ISSUE TITLE
Add GetInputs() and GetOutputs() functions

### ISSUE THREAD

**Issue by bhaney** [yalue/onnxruntime_go#38]
Thanks so much for creating this repo! It's worked really well for running my ONNX models from Go.

I was wondering if convenience functions could be added to make it easier to know what the input/output tensor shapes of a model are. With the way things are now, I build a new Go program for every ONNX model I have, since the `NewSession` function has to have the input and output tensors from the beginning.

I'm not sure if it would be easier to create something like `GetInputs(modelPath)` and 'quickly' create a session just to get the input tensor's name/shape/type, or maybe there is a reason you wouldn't want to include a function like this in the module.

**Comment by yalue** [comment]
Thank you, and I'm happy this project has helped!

Unless I'm misunderstanding your question, I already have a function like that in the module: [`GetInputOutputInfo`](https://pkg.go.dev/github.com/yalue/onnxruntime_go#GetInputOutputInfo), which returns two slices: one containing information for each input and one containing information for each output.  Each input or output's name, size, and type is provided in a corresponding [`InputOutputInfo`](https://pkg.go.dev/github.com/yalue/onnxruntime_go#InputOutputInfo) struct.  I added this relatively recently, in response to issue #31.

For example:
```go
inputs, outputs, err := onnxruntime_go.GetInputOutputInfo("path/to/file.onnx")
if err != nil {
    // ...
}

for i, input := range inputs {
    fmt.Printf("Input %d: name=%s, shape=%s, type=%s\n", i, input.Name, input.Dimensions, input.DataType)
}

// And outputs can be checked similarly.
```

I hope this is what you're looking for; let me know if I'm not understanding!

**Comment by bhaney** [comment]
Awesome! Thanks, I didn't see it in the documentation here, so didn't know it was available https://pkg.go.dev/github.com/yalue/onnxruntime#section-readme

It was exactly what I was looking for
