### ISSUE TITLE
how to use gpu with onnxruntime_go package?

### ISSUE THREAD

**Issue by WonhoiKim** [yalue/onnxruntime_go#4]
hi i am using your onnxruntime_go package. Thank you very much for making the package and I have one question.
I use the package to inference, but I'm using the cpu, not the gpu. Is there any way to use the gpu?

The version I'm using is:
onnxruntime:1.15.1
cuda: 11.8
cudnn:8.6.0

**Comment by topazape** [comment]
Hi, How about using this library instead of Yalue's?
https://github.com/peer-ai-org/onnxruntime_go

It seems to be a fork of `yalue/onnxruntime_go` and has the `NewSessionWithPathWithTypeWithCUDA` function. So, you might be able to use a GPU.

**Comment by yalue** [comment]
Hi @WonhoiKim, thank you for the interest in the project.  Unfortunately, @topazape is correct.  I do not currently have GPU support in this version.  I may add it later, but do not have much time to work on the project.  The fork looks like a reasonable alternative for the time being.
