### ISSUE TITLE
Add support for dynamic shapes

### ISSUE THREAD

**Issue by Straffern** [yalue/onnxruntime_go#41]
Hello, I am currently trying to get a model working in a golang project. The model accepts a dynamic input size, and also outputs a list of dynamic shapes.

Is this possible or is there another way?

**Comment by yalue** [comment]
Hello,

I do not think it's currently possible with this project, unfortunately.  (More due to the dynamic outputs than the dynamic inputs.)  However, this is something that I've been wanting to work on personally, though I don't know when I'll get around to adding it yet.

It's possible that the work done in PR #24 will help with dynamically sized outputs, but I just don't yet know how much work remains to support this properly.  I'd also be happy to look at a PR if you or anyone else wants to work on this issue.

**Comment by yalue** [comment]
A quick update on this: fortunately, it actually is possible!  I added a quick test case in commit e3c08ba13619230a02b9c.  The key is to use `DynamicAdvancedSession` with the automatic output allocation introduced in PR #24.  So, something like this:

```go
// Create a DynamicAdvancedSession instance
session, err := ort.NewDynamicAdvancedSession("path/to/net.onnx", []string{"input_name"}, []string{"output_name"}, nil)
if err != nil {
    // ...
}
defer session.Destroy()

// We'll assume the network takes a dynmic shape with an arbitrary batch of vectors containing 5 elements.
// Start by creating a 123x5 input tensor
firstInput, err := ort.NewEmptyTensor[float32](NewShape(123, 5))
if err != nil {
    // ...
}
defer firstInput.Destroy()
// Fill the firstInput tensor

// We'll also create a 456x5 input tensor
secondInput, err := ort.NewEmptyTensor[float32](NewShape(456, 5))
if err != nil {
    // ...
}
defer secondInput.Destroy()

// We'll create an array of ArbitraryTensors containing a single nil entry, indicating that we want our
// single output tensor to be allocated by onnxruntime
firstOutputs := []ArbitraryTensor{nil}

// Run the session with the 123x5 input
err = session.Run([]ArbitraryTensor{firstInput}, firstOutputs)
if err != nil {
    // ...
}
// If Run() succeeded, it will have allocated the output tensor, which we'll need to make sure to destroy
defer firstOutputs[0].Destroy()

// Run the session with the 456x5 input
secondOutputs := []ArbitraryTensor{nil}
err = session.Run([]ArbitraryTensor{secondInput}, secondOutputs)
if err != nil {
    // ...
}
defer secondOutputs[0].Destroy()
```

Admittedly it's still a bit of a hassle, but I wanted to update this issue with the news that yes, it's possible.  It ought to also work if you manually allocate your output tensor, if you know its size ahead of time.  Eventually, I may still try to make this a bit more convenient, but at least it seems to work for now, and there's now a test case in place to ensure that it stays that way.
