### ISSUE TITLE
SessionOption `enable_mem_reuse` Support

### ISSUE THREAD

**Issue by FelixHo** [yalue/onnxruntime_go#46]
Hi, thanks for the great job. Can you add support for the configuration option `enable_mem_reuse` in session options?

**Comment by yalue** [comment]
Hi, and thank you!  Unfortunately, enable_mem_reuse is only part of the C++ API, and hasn't been exposed in the purely C API, `onnxruntime_c_api.h`, which I use for this project.  It may be possible that some workaround may exist, but I am not particularly hopeful.  The place where this would need to be resolved would ideally be in onnxruntime itself---requesting that _they_ add `enable_mem_reuse` to the C API.  If that were the case I would be able to expose the API here as well.
