### ISSUE TITLE
Can one use this package in production?

### ISSUE THREAD

**Issue by liufuyang** [yalue/onnxruntime_go#5]
Hi @yalue, thanks for creating this tool for the Golang world. I am new to ONNX domain and a bit surprised to see no official Golang support there.

Do you think the ONNX APIs are relatively stable and perhaps it is fine for one to use your package in production? And do you see some potential problems later we might encounter if we do that? And would it be simple to fix or add some features with or without your help? On our side, we have very limited knowledge of Golang C bindings.

The actual need on our side is to be able to deploy/serve models created by some framework in our Golang backend environment.

Thank you very much.

**Comment by liufuyang** [comment]
Thank you very much for providing such useful information. We decided to give your package a try and if possible we can also provide some help in maintaining it. Personally, I have zero knowledge in Golang's C bindings, but I don't mind learning more later if needed. And I feel your package here has a relatively good code and good documentation to let us easily start loading an ONNX model. So thanks for the good work again 👍

**Comment by kampaidev** [comment]
Yes, made predictions on a 1gb vps using this library, being req thousands of times a second, no issue and ran smoothly. Also keep in mind this 1gb vps is running 3 other servers as well.
