### ISSUE TITLE
An error is displayed when CUDA is invoked

### ISSUE THREAD

**Issue by zhaoyanan2452** [yalue/onnxruntime_go#58]
Hello, I call CUDA on my jetson orin nx device and I get the following error message, cuda version is 11.4 , onnxrungtime version 1.18.

code：
	cuda, _ := ort.NewCUDAProviderOptions()
	defer cuda.Destroy()
	cuda.Update(map[string]string{"device_id": "0"})
	options.AppendExecutionProviderCUDA(cuda)

	// options.SetIntraOpNumThreads(3)
	// options.SetInterOpNumThreads(3)

	session, _ := ort.NewAdvancedSession(`/home/jetson/golangspace/mygocv/model_sim.onnx`,
		[]string{"images"}, []string{"output0"},
		[]ort.ArbitraryTensor{inputTensor},
		[]ort.ArbitraryTensor{outputTensor},
		options)

Error `message：`

panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4def58]

goroutine 1 [running]:
github.com/yalue/onnxruntime_go.(*CUDAProviderOptions).Destroy(0x40000021c0?)
        /home/jetson/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.10.0/onnxruntime_go.go:627 +0x18
panic({0x519b20?, 0x60d350?})
        /usr/local/go/src/runtime/panic.go:770 +0x124
github.com/yalue/onnxruntime_go.(*CUDAProviderOptions).Update.func1(0x4000054d28?, {0x400011c028, 0x1?, 0x184fcf0?}, {0x400011c030, 0x4df070?, 0x532293?}, 0x2?)
        /home/jetson/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.10.0/onnxruntime_go.go:614 +0x4c
github.com/yalue/onnxruntime_go.(*CUDAProviderOptions).Update(0x0, 0x4000054d28)
        /home/jetson/go/pkg/mod/github.com/yalue/onnxruntime_go@v1.10.0/onnxruntime_go.go:615 +0xec
main.initSession()
        /home/jetson/golangspace/mygocv/image_detect.go:136 +0x1e4
main.run()
        /home/jetson/golangspace/mygocv/image_detect.go:36 +0x90
main.main()
        /home/jetson/golangspace/mygocv/image_detect.go:25 +0x1c
exit status 2

**Comment by yalue** [comment]
I expect that CUDA isn't actually supported or properly configured on your system.  This should cause an error to be returned by `NewCUDAProviderOptions` and/or `NewAdvancedSession`,  so I highly recommend checking the error returns from both of those functions.  If you still get a segfault while neither of those functions return an error, feel free to re-open this issue.

In your particular case the segfault / nil pointer issue is almost certainly caused by NewCUDAProviderOptions returning nil due to CUDA not being supported by your build of onnxruntime, missing CUDA libraries on your system, versions of the CUDA libraries that aren't supported by onnxruntime, missing cudnn libraries, or problems along those lines.

**Comment by yalue** [comment]
Looking at your comment again, I see that you're using CUDA 11.4, which isn't supported by onnxruntime 1.18.  So you'll probably need to figure out how to update CUDA to 11.8 or 12.4.  See the list of supported CUDA versions for onnxruntime here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by zhaoyanan2452** [comment]
Thanks for the suggestion, I compiled the onnxruntime runtime on my jetson device and the runtime prompt is as follows, how should I load libonnxruntime_providers_cuda.so

**Comment by zhaoyanan2452** [comment]
Thanks for the suggestion, I compiled the onnxruntime runtime on my jetson device and the runtime prompt is as follows, how should I load libonnxruntime_providers_cuda.so

/home/jetson/Downloads/onnxruntime-1.17.3/onnxruntime/core/session/[provider_bridge_ort.cc:1209](http://provider_bridge_ort.cc:1209/) onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library [libonnxruntime_providers_cuda.so](http://libonnxruntime_providers_cuda.so/) with error: [libonnxruntime_providers_cuda.so](http://libonnxruntime_providers_cuda.so/): cannot open shared object file: No such file or directory
