### ISSUE TITLE
how to reuse the session for many different input

### ISSUE THREAD

**Issue by oldfo4** [yalue/onnxruntime_go#6]
as shown in the example usage, the session was destoried after run once, how to reuse the session for other different inputData? Thank you.

**Comment by yalue** [comment]
Hi,

You can simply update the data in the input tensor (or tensors, if you have multiple inputs), and then call the session's `Run()` function again.  Every time you call `session.Run()`, the current contents of the input tensor will be re-read, and the output tensor will be re-written.  The session itself should be usable no matter how many times you call `session.Run()`.

As a brief example:

```go
    // ...
    inputTensor, err := ort.NewEmptyTensor[float32](inputShape)
    defer inputTensor.Destroy()
    outputTensor, err := ort.NewEmptyTensor[float32](outputShape)
    defer outputTensor.Destroy()

    session, err := ort.NewSession[float32]("path/to/network.onnx",
        []string{"Input 1 Name"}, []string{"Output 1 Name"},
        []*Tensor[float32]{inputTensor}, []*Tensor[float32]{outputTensor})
    defer session.Destroy()

    inputTensorUnderlyingData := inputTensor.GetData()
    outputTensorUnderlyingData := outputTensor.GetData()
    
    // This loop assumes the hasMoreInputData() returns a boolean if more inputs are needed, and
    // the getNextInputData() function returns a slice of float32's of the same size as the input tensor's
    // underlying data.
    for hasMoreInputData() {
        copy(inputTensorUnderlyingData, getNextInputData())
        err := session.Run()
        processOutputData(outputTensorUnderlyingData)
    }
```

I hope this helps!

**Comment by yalue** [comment]
Hello again, updating this issue in case someone looks at it in the future:

As of commit 7bf5a6e (PR #14), the library now supports the `DynamicSession` and `DynamicAdvancedSession` types, which despite their long names, are no more difficult to use than the old `Session` and allow passing lists of input and output tensors to their `Run(...)` functions.
