### ISSUE TITLE
bindings to onnxruntime generate api

### ISSUE THREAD

**Issue by riccardopinosio** [yalue/onnxruntime_go#68]
Onnx recently introduced a C api for generative models:

https://github.com/microsoft/onnxruntime-genai/blob/main/src/ort_genai_c.h

Although still in preview, the advantage of the API is that it makes it easier to do the generate() inference cycle for generative models rather than having to implement it on the basis of the base C api.
I am considering writing bindings for it. Since models seem to be loadable only from paths for this one, it would probably only work on linux for the moment (like the onnxruntime training bindings).
@yalue how do you feel about it:?

**Comment by yalue** [comment]
Even though it's dependent on onnxruntime, that API is meant for an entirely separate DLL/shared library and not part of onnxruntime itself.  In fact, the releases for that library bundle a copy of onnxruntime.so/dll.  My preference would be to keep this repository strictly for the base onnxruntime and not include additional binaries or APIs.

That being said, I am happy to see that onnxruntime-genai includes a C API, so you could probably make a Go package using a similar cgo technique to the one I used in `setup_env.go`/`setup_env_windows.go`.  That is, you could try loading `onnxruntime-genai.so` using dlopen/dlsym on Linux, or using `syscall.LoadLibrary` on Windows, and use the same `#include` tricks (along with the associated pitfalls!) to create a cgo wrapper.  Loading `onnxruntime-genai.so` (or DLL) should automatically attempt to load the copy of `onnxruntime.so` bundled in the release, so I don't think the `onnxruntime` portion of the API would even need management from Go in a hypothetical `onnxruntime-genai-go` wrapper.  Let me know if you see things differently!

**Comment by yalue** [comment]
I'd be happy to look over it, though no guarantees.  Unfortunately, this type of stuff falls farther and farther outside of what I have been using onnxruntime for personally, so I probably won't have much to say about generative AI applications.  I'd still be happy to glance at the CGo-related code when it's ready, though.
