### ISSUE TITLE
how to use scalar input

### ISSUE THREAD

**Issue by pablodz** [yalue/onnxruntime_go#7]
Hello there, 

how to use a scalar tensor?

**Comment by yalue** [comment]
Hello,

Are you referring to using a tensor containing just a single element?  If so, you should just be able to create a single-element tensor, with a one-dimensional shape:

```go
// Create a single-element 1D scalar tensor (error checking omitted)
scalarShape := onnxruntime_go.NewShape(1)
scalarTensor, err := onnxruntime_go.NewEmptyTensor[float32](scalarShape)

// Create the session, specifying the scalar tensor as an input
// (This snippet assumes you've already created the float32 outputTensor)
session, err := onnxruntime_go.NewSession[float32]("path/to/network.onnx", []string{"ScalarInput"},
    []string{"OutputName"}, []Tensor{scalarTensor}, []Tensor{outputTensor})

// Set the input scalar value to 1337.0 (or whatever you need it to be)
scalarTensor.GetData()[0] = 1337.0

//  And eventually...
err = session.Run()
```

I hope this helps.  The library does not currently provide any simpler way for supporting scalar inputs, apart from using 1D single-element tensors.

**Comment by pablodz** [comment]
It helps, I'm trying to implement this type of nn

![image](https://github.com/yalue/onnxruntime_go/assets/28235457/d3a4c68b-3e65-4b7f-b768-0503f67a69b3)

where sample rate is int64, but tensor is like a mixed types `NewSession[float32]`

**Comment by yalue** [comment]
Ah, I see.  So it looks like you need multiple inputs with different types?  In that case, I believe this may be supported by a fork of this project: that seems to have many additional features https://github.com/peer-ai-org/onnxruntime_go/.  At the moment, my own project does not support multiple different input types, I am sorry about that!  I hope the fork has what you need; I haven't used it myself, but glancing over the code they seem to support a far greater number of onnxruntime features.  Good luck!

**Comment by pablodz** [comment]
Thank you

**Comment by yalue** [comment]
Hello again,

Just commenting on this issue to note for future readers that this is now supported as of commit 7bf5a6e (PR #14).  The new `AdvancedSession` type allows arbitrary mixing of input tensor types; you can now provide input or output tensors consisting of mixes of `int32`s, `float64`s, or any other `TensorData` type.
