### ISSUE TITLE
Upgrade to onnxruntime version 1.20.0

### ISSUE THREAD

**Issue by yalue** [yalue/onnxruntime_go#71]
It's that time again!  Onnxruntime 1.20.0 is out.  Upgrading will hopefully require following the [same checklist as before](https://github.com/yalue/onnxruntime_go/issues/54#issuecomment-2125442196).

**Comment by RJKeevil** [comment]
Tada: https://github.com/yalue/onnxruntime_go/pull/72

As mentioned, please confirm tests pass, and consider removing training support what was deprecated this release.

**Comment by yalue** [comment]
Fixed as of PR #72

**Comment by yalue** [comment]
Onnxruntime 1.20 is now supported by tagged version `v1.13.0` of `onnxruntime_go`.
