### ISSUE TITLE
Does the library supports tensor of bool?

### ISSUE THREAD

**Issue by razor182** [yalue/onnxruntime_go#76]
Hi everyone. 

I have the model, which expected tensor(bool) for input:
`2 inputs to model.onnx:`
  `Index 0: Tensor "t1": [-1 -1 256], ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT`
  `Index 1: Tensor "t2": [-1 -1], ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL`

But ort.TensorData not support bool...
Is there a solution how to create a tensor of bool with ort.NewTensor constructor?

**Comment by razor182** [comment]
I found a solution: convert []bool -> []byte and use NewCustomDataTensor constructor.

Example:

   ```
    tensorByte := make([]byte, len(tensorBool))
    for i, v := range tensorBool{
        tensorByte[i] = 0
        if v {
            tensorByte[i] = 1
        }
    }

    inputShape := ort.NewShape(int64(batchSize), int64(tranzCnt))
    inputTensor, err := ort.NewCustomDataTensor(inputShape, tensorByte, ort.TensorElementDataTypeBool)
```

**Comment by yalue** [comment]
Sorry for the slow response, but I'm glad to hear that `CustomDataTensor` worked for you.  I admit it would be nice to support `NewEmptyTensor[bool](...)` in the future, though.  The one reservation is that I'd need to be sure that Go's `bool` type will always be represented by a single byte, matching what onnxruntime expects.  At the moment, it is indeed OK; `unsafe.Pointer(&(myBoolSlice[0]))` does point to an underlying slice containing one byte per bool.  However I would prefer to find any mention in the Go specification that this will always be the case in the future.  For example, if Go ever "optimizes" bool slices to be bit sets (i.e., C++'s `vector<bool>`), then this would be broken.

Probably I'll just go ahead and add `Tensor[bool]` support anyway, and add special cases to do manual conversion if Go ever moves away from one-byte-per-bool

**Comment by yalue** [comment]
`Tensor[bool]` is now supported in the library as of PR #77, and in tagged version `v1.14.0`.  Let me know if you use it and encounter problems.
